import React from 'react'

const Sustinabletourims = ({ crs }) => {
    return (
        <div class='content'>
            <div className='topic-cc'>{crs}</div>
            //week 1
            <p className='cc-boxes'>
                &nbsp;1:&nbsp;Since the 1950’s international tourist arrivals have increased from 25 million globally, to 527 million in 1995, and 1.2 billion in 2016. How many billion of international tourist arrivals (annually) are expected  by 2030?< br />
                &nbsp;<strong class='ans'>1.8 billion </strong>< br />
               
            </p>
            <p className='cc-boxes'>&nbsp;2:&nbsp;According to figures from the International Air Transport Association (IATA) it is estimated that airline passengers during transport generated 5.2m tons of waste in 2016. The figure is expected to…< br />
                
                &nbsp;<strong class='ans'>… double by 2030</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;3:&nbsp; As presented in the report Tourism Highlights 2017, The World Tourism Organisation (UNWTO), estimates   that the tourist arrivals between 2010 and 2030, with regard to both emerging destinations and advanced economies, respectively, will what < br />
                
                &nbsp;<strong class='ans'>The, arrivals in emerging destinations (+4.4% a year) are expected to increase annually at twice the rate of those in advanced economies (+2.2% a year). </strong><br />
               
            </p>
                        <p className='cc-boxes'>&nbsp;4:&nbsp; Which of the charts below shows according to UNWTO the correct distribution between means of transportation by tourists in 2018?   < br />
                
                &nbsp;<strong class='ans'>air (58%), road (37%), rail (2%), water (4%) </strong><br />
               
            </p>
                        <p className='cc-boxes'>&nbsp;5:&nbsp;The World Bank provides open data on International tourism arrivals. Please explore the data. How many international arrivals do you find respectively for Indonesia and Caribbean Small States for the years 2000 and 2015?    < br />
                
                &nbsp;<strong class='ans'>Year 2000: Indonesia: 5.064.000, Caribbean Small States 11.115.377 - Year 2015: Indonesia: 10.407.000, Caribbean Small States 17.200.000  </strong><br />
               
            </p>
                        <p className='cc-boxes'>&nbsp;6:&nbsp;According to Professor Stefan Gössling, the World Tourist Organisation and many governments in developing countries focus upon growth in the tourist sector. This supports the paradigm that  tourism is a growth sector supporting e.g. job creation  for a low skilled workforce . However, Prof. Gössling calls for a different discussion about tourism – What question would Gössling like to discuss?    < br />
                
                &nbsp;<strong class='ans'> What does the money actually do within the destinations? </strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;7:&nbsp; The UNWTO report, Tourism and the Sustainable Development Goals, Journey to 2030 – Highlights, mentions some of tourism’s challenges and threats, including irresponsible consumption and production and poor management of resources and waste. The achievement of which SDG's are the most impacted by  these Challenges and threats (multiple correct answers). < br />
                
                &nbsp;<strong class='ans'> SDG 14 ‘Life below Water’. </strong>
                &nbsp;<strong class='ans'>SDG 12 ‘Responsible Consumption and Production’. </strong>
                &nbsp;<strong class='ans'>SDG 11 ‘Sustainable Cities and Communities’  </strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;8:&nbsp; Which statement describes correctly the employment situation for Zanzibaris in the tourism sector on Zanzibar? < br />
                
                &nbsp;<strong class='ans'>Zanzibaris hold 11% of managerial positions in restaurants and 46% in hotels compared with 83% and 70% of unskilled jobs in hotels and restaurants, respectively</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;9:&nbsp;Even though the tourist industry has a capacity for economic growth for local communities, it is not always the case. A study from Zanzibar published in 2015 found that… < br />
                
                &nbsp;<strong class='ans'> 20% of the GDP generated by tourism accrued to local communities; 15% went to the government in the form of taxes and 12% to Zanzibaris from outside the local communities. Non-Zanzibaris, from mainland Tanzania and other countries, obtain 53% of tourism GDP  </strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;10:&nbsp;As one of the fastest growing economic sectors in the world, tourism is increasingly recognized as a vital contributor to job and wealth creation, environmental protection, cultural preservation and poverty alleviation. However, this is far from always happening because…< br />
                
                &nbsp;<strong class='ans'>the failure of the state to fulfil its responsibilities to translate the opportunities presented by tourism into social and economic development or ‘public goods’. </strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;11:&nbsp;Associate Professor Stig Jensen highlight that the growing number of tourists from Africa traveling to other destinations in Africa, may contribute more economically per person to the local communities than the tourists from North e.g. Europe. Why? (select 4 answers).  < br />
                
                &nbsp;<strong class='ans'>(Except this one) They spend money shopping in big malls</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;12:&nbsp;Tourist sustainability certification can (Source: Dodds & Joppe, 2005)” be described as:< br />
                
                &nbsp;<strong class='ans'>The process of assuring industry and consumers that the assessed company has met a set of minimum standards. The purpose of certification has been to achieve voluntary standards which meet or exceed baseline standards or legislation”</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;13:&nbsp;The sustainability certification schemes can be divided into three main types. Below you see short statements on each type as described by Professor Flemming Konradsen. One of the statements has been manipulated and is no longer correct. Which one?< br />
                
                &nbsp;<strong class='ans'>The second level certification is where a local or international organisation develops a set of criteria for a business or destination for them to meet. It could be based on local needs and priorities and may even follow international standards. The organisation responsible for the content of the criteria will not check nor approve the destination or business </strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;14:&nbsp;In the interview, Niels Riis Jensen mentions GSTC. GSTC or the Global Sustainable Tourism Council is an independent, neutral non-profit organization which establishes and manages global sustainable standards, GSTC Criteria. These criteria are “the guiding principles and minimum requirements that any tourism business or destination should aspire to reach in order to protect and sustain the world’s natural and cultural resources, while ensuring tourism meets its potential as a tool for conservation and poverty alleviation.”.  GSTC has two sets of criteria. Which? (multiple correct answers).< br />
                
                &nbsp;<strong class='ans'>Destination Criteria</strong>
                &nbsp;<strong class='ans'>Industry Criteria</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;15:&nbsp;Niels Riis Jensen recognizes that it is costly and in other ways demanding to achieve an internationally approved third level certification. To facilitate the procedure, he suggests small hotels to…< br />
                
                &nbsp;<strong class='ans'>… pool knowledge among more hotels and work together</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;16:&nbsp;The survey Environmental Sustainability in the Hospitality Industry: Best Practices, Guest Participation, and Customer Satisfaction,  gives a strong indication “that travelers who do not participate in hotels’ green programs would be willing to do so if they were given incentives. Although many guests’ green behavior is motivated by their personal beliefs, the survey found that others would respond to rewards, including frequent guest points or food vouchers.”. How big a percentage of guests who are not currently participating in hotels’ green programs would according to the survey take action if rewards were offered?< br />
                
                &nbsp;<strong class='ans'>More than 80%</strong><br />
               
            </p>
            //week 2
            <p className='cc-boxes'>&nbsp;17:&nbsp;How many hotels are according to a study from 2012 built closer to the sea than accepted by national regulation on Zanzibar?< br />
                
                &nbsp;<strong class='ans'>60%</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;18:&nbsp;Peter Stæhr and his colleges conducted a water quality baseline survey around the Unguja Island in 2015. Where did they find the highest level of coliform bacteria?< br />
                
                &nbsp;<strong class='ans'>Off the northern and north-eastern part, suggesting a strong impact from the resorts located along the coastline</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;19:&nbsp;The vast majority of hotels on Zanzibar…< br />
                
                &nbsp;<strong class='ans'>… use septic tanks or discharge the sewage directly into the sea</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;20:&nbsp;Peter Stæhr and his colleges have found that almost half of the marine litter they found as part of their research consisted of plastic. According to the United Nations Development Programme, how many pieces of plastic litter are on average found on every square kilometer of ocean? Please write the exact number below.< br />
                
                &nbsp;<strong class='ans'>13000</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;21:&nbsp;One of the targets within Sustainable Development Goal 14 ‘Life below Water’ is to “increase the economic benefits to Small Island developing States and least developed countries from the sustainable use of marine resources” Is sustainable management of tourism seen as part of the solution?< br />
                
                &nbsp;<strong class='ans'>Yes</strong><br />
               
            </p>


            <p className='cc-boxes'>&nbsp;22:&nbsp;Why are coral reefs considered to be of major importance to conserve? Because coral reefs… (Select the five correct answers).< br />
                
                &nbsp;<strong class='ans'>(Except these two)… are a major source of building material, … protects against climate change…</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;23:&nbsp;Coral reefs are not only suffering from coral bleaching linked with rising sea temperatures but also from tourism and recreational impacts. Which so called stressors are according to Reef Resilience Network, stressing the coral reefs (multiple correct answers).< br />
                
                &nbsp;<strong class='ans'>(Except these two) Ocean Acidification, Oil spill</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;24:&nbsp;Researcher Ali Ussi explained that corals looking like these in the middle of the picture is an example of:< br />
                
                &nbsp;<strong class='ans'>Soft corals, with algae growth due to excessive levels of nutrients in the marine environment</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;25:&nbsp;An important quote from the interview with Dr. Arias-González was:< br />
                
                &nbsp;<strong class='ans'>“Climate change happens long term” (…) ”The massive development happening right now is much more dangerous</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;26:&nbsp;graph  < br />
                
                &nbsp;<strong class='ans'>The number of cruise ship arrivals can precipitate a shift from a healthy reef system to a degraded state characterized by low coral cover and dominance of alga.</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;27:&nbsp;bar graph< br />
                
                &nbsp;<strong class='ans'>Out of the 21 countries, 14 countries have higher per-tourist water consumption compared to local communities whereas seven high income countries show a reverse relationship with the local population consuming more water per day</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;28:&nbsp;In the video, 'Tourism and ’reshwater demands’, Prof. Gössling suggests thatit might be a better idea to rethink how we use water, rather than solving theproblem of water scarity through desalination plants. What is the reasoning behind this suggestion?< br />
                
                &nbsp;<strong class='ans'>The use of energy and brine discharged into the sea from the desalination plants </strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;29:&nbsp;Tourists׳ water use on a per guest basis was according to the study Water equity - Contrasting tourism water use with that of the local community found to differ substantially. Which of all countries surveyed shows the highest tourism contribution to municipal water withdrawal?< br />
                
                &nbsp;<strong class='ans'>Fiji</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;30:&nbsp;According to calculations by Prof. Gössling, Zanzibar has a great water disparity. How big a percentage of Zanzibar’s population is deprived of safe drinking water?< br />
                
                &nbsp;<strong class='ans'>15%</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;31:&nbsp;According to calculations by Prof. Gössling, Zanzibar has a great water disparity. How many times higher is the daily water use per tourist compared to local residents.< br />
                
                &nbsp;<strong class='ans'>15</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;32:&nbsp;What happens when a freshwater pump on land is shut off because the water has turned saline?< br />
                
                &nbsp;<strong class='ans'>The freshwater will flow on top of a saltwater “lens” </strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;33:&nbsp;According to the Zanzibar Water Authority (ZAWA):< br />
                
                &nbsp;<strong class='ans'>Zanzibar needs production of more than 200 million litres of freshwater for its people, but only less than 50 per cent of the requirement is generated and distributed to the population</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;34:&nbsp;From the study Groundwater on Zanzibar - use and pollutants a survey among 372 villagers complaints related to freshwater on Zanzibar showed the following distribution:< br />
                
                &nbsp;<strong class='ans'>Salinity (66 %), Bad smell (17 %), Causing illness (8 %), Insufficient quantity (4 % in wells), Insufficient supply (3 % in pipes), Dirt (1 %)</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;35:&nbsp;The study Groundwater on Zanzibar - use and pollutants shows that 75.7% of villagers regularly uses more than one well. For which reasons?< br />
                
                &nbsp;<strong class='ans'>Salinity (83,6), Quantity (11,8), Quality (1,8), Access (1,8), Access/Quantities (0,9)</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;36:&nbsp;For all three Zanzibar villages, Kiwengwa, Nungwi and Jambiani surveyed in the study Maximising Benefits from Water For Tourism in Africa, findings show an average water use per households of 93.2 liters per day while the use per room per day for tourists ranging from:< br />
                
                &nbsp;<strong class='ans'>686 litres per day for guesthouses to 3,195 litres per day for 5-star hotels.</strong><br />
               
            </p>
            //week 3
            <p className='cc-boxes'>&nbsp;37:&nbsp;Professor Flemming Konradsen refers to a study Solid Waste Generation and Associated Problems of Selected Tourism Destinations in Kerala, India saying that the per capita waste generation per day in India in 2011 is 0.5 kg. Among Indian tourists in Kerala the amount is 3.5 kg per day, but how many per cent more than an Indian tourist does a foreign tourist generate per day?< br />
                
                &nbsp;<strong class='ans'>5714%</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;38:&nbsp;Is it true that environmental health risks for regulated dump sites, include contamination of ground water and surface water?< br />
                
                &nbsp;<strong class='ans'>Yes</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;39:&nbsp;Which of the following statements is correct?< br />
                
                &nbsp;<strong class='ans'>Higher </strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;40:&nbsp;A strategy of building a stronger integrated solid waste management system at tourist destinations would follow the generally accepted hierarchy of waste management priorities. Which would be the least environmentally and resource friendly way for hotels to manage waste is?< br />
                
                &nbsp;<strong class='ans'>Dumpsite</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;41:&nbsp;The study 'Tourism Induced Challenges in Municipal Solid Waste Management in Hill Towns: Case of Pahalgam' , found that in the small hill town, Pahalgam, located in the northern Indian state Jammu and Kashmir, Guest Houses constitute 65% of the total accommodation but constitute only 18% of the total solid waste from the accommodation sector, whereas A- Class Hotels constitute only 7% of the total accommodation sector but contribute more than 35% of the total waste. How many kg of waste are respectively generated per day per guest in: A-Class B-Class C-Class Guest House?< br />
                
                &nbsp;<strong class='ans'>A-Class: 2.9 kg B-Class: 1.9 kg C-Class: 1.7 kg Guest House: 0.9 kg</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;42:&nbsp;In a publication from Zanrec, it says “Due to an absence in policy and lack of access for both community and hotels to proper waste management, an equivalent of the weight of a Boeing 747 gets dumped uncontrolled into Zanzibar’s environment every day, contaminating the environment and causing serious implications to public health and the tourism industry”. According to the same publication, how many tourists a) complain about the poor waste management on Zanzibar and how many consider b) not returning to Zanzibar because of the garbage they saw during their stay.< br />
                
                &nbsp;<strong class='ans'> 1 out of 3 </strong>
                &nbsp;<strong class='ans'>4 out of 5</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;43:&nbsp;According to Professor Flemming Konradsen local researchers on Zanzibar find that most of the solid waste in Zanzibar is generated at hotels, bars, restaurants and shops. How much of this waste is currently collected for proper disposal?< br />
                
                &nbsp;<strong class='ans'>20%</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;44:&nbsp;Why has Zanrec a specific focus on enabling access to sustainable waste management for hotels and not for for example for food producers or market places? < br />
                
                &nbsp;<strong class='ans'>The government on Zanzibar has stated that they do not have the capacity to manage solid waste generated by hotels and no other programs support sustainable waste management on the island. </strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;45:&nbsp;What strategy does Assistant Lecturer Aziza Suba Abdulakadir suggest to pursue as a first step to establish sustainable waste management on Zanzibar?< br />
                
                &nbsp;<strong class='ans'>Sorting</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;46:&nbsp;Around 5 million plastic bottles are consumed at hotels by tourists every year on Zanzibar. While some bottles end up in the environment others are collected by Zanrec. What happens according to General manager at Zanrec, Justin Madho, with the plastic after it is collected by Zanrec?< br />
                
                &nbsp;<strong class='ans'>Agents collect it, shred it and send it to Dar es Salaam from where it is send to China for recycling</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;47:&nbsp;Few tourists consider how tourism add to the number of mosquito breeding places and how an increased use of chemical insecticides can lead to mosquito insecticide resistance. In case of a disease outbreak it may no longer be possible to control such an outbreak. Which diseases are related to Aedes mosquitoes?  (multiple correct answers). < br />
                
                &nbsp;<strong class='ans'>(Except this one) Malaria </strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;48:&nbsp;Fatma Saleh mentions that hotels could reduce the mosquito abundance tremendously by looking at the breeding sites within the hotel compound rather than spraying with insecticides. She recommends hotels to implement environmental management practices, for example by… (multiple correct answers).< br />
                
                &nbsp;<strong class='ans'>(Except these two) … covering swimming pools during the night, ….. removing outdoor showers</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;49:&nbsp;Environmental management for mosquito control seeks to manage the environment in order to decrease the number of mosquitoes and to limit human-mosquito contact, includingby “destroying, altering, removing or recycling non-essential containers that provide egg/ larval/ pupal habitats”. Environmental management for mosquito control  is divided into three different types of interventions. How are the three types of environmental management defined by WHO? (multiple correct answers).< br />
                
                &nbsp;<strong class='ans'>(Except these two) Changes to mosquito habitation, Environmental elimination</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;50:&nbsp;According to WHO, water-storage containers can be mosquito proofed by designing them to prevent mosquitoes from laying eggs on the surface of the water. Which strategies can be used? (multiple correct answers)< br />
                
                &nbsp;<strong class='ans'>(Except these two) A tall net needs to be placed at the perimeter of the hotel compound to prevent mosquitoes from entering, Electronic devices generating a very specific sound needs to be installed outside the hotel rooms to prevent mosquito entry</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;51:&nbsp;In the podcast Mapping Mosquitoes, it is mentioned that dengue fever and chikungunya transmitted by two types of Aedes mosquito have become a public health problem the last 20 or 30 years, partly because of increased human mobility, such as people travelling to certain places where the virus was once detected. A scientist from Oxford University, Moritz UG Kraemer has pooled the data from across the world to produce the first distribution map for these mosquitoes. What was his purpose? Kraemer wanted to map the the global distribution of Aedes mosquitoes…< br />
                
                &nbsp;<strong class='ans'> to be able to measure how effective future implemented controls will be in certain regions</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;52:&nbsp;From which country have the Authorities publicly announced a reduction in tourist activities to protect the environment from overcrowding? < br />
                
                &nbsp;<strong class='ans'>Thailand</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;53:&nbsp;A Minister of Tourism and Culture declared in 2015: “We don’t want to demean the value of the X-country. We’re reaching 250,000 people, six times the number of people who live there.” Which country is the minister referring to?< br />
                
                &nbsp;<strong class='ans'>Seychelles</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;54:&nbsp;Stig Jensen suggests to compare the situation on Zanzibar with Mallorca and exchange experiences. Which specific challenge does he mention as an example of similarity?< br />
                
                &nbsp;<strong class='ans'>Water scarcity</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;55:&nbsp;What does Stefan Gössling roughly respond to the question: “How should collaboration unfold to move towards a 2030 Agenda on Zanzibar”?< br />
                
                &nbsp;<strong class='ans'>Very much depend on government and political decisions but it is important to involve the tourism industry on one hand and local stakeholders that can develop small businesses on the other hand</strong><br />
               
            </p>
            <p className='cc-boxes'>&nbsp;56:&nbsp;According to an article from Global Voices, Palau has been the first in the world to introduce an immigration-related reform to promote environment awareness and protect the environment. Palau President Tommy Remengesau issued a decree December 6, 2017, requiring visitors to sign an eco-pledge on their passports before being granted a visa upon arrival. But does the visa stamp really says “The only footprint I shall leave are those that will wash away”?< br />
                
                &nbsp;<strong class='ans'>Yes</strong><br />
               
            </p>
           
           

            
            
            
        </div>
    )
}

export default Sustinabletourims